// web/src/components/GameWindow.tsx
import { useCallback, useEffect, useRef } from "react";
import type Game from "../lib/game";

type GameWindowProps = {
  game: Game;
};

export default function GameWindow({ game }: GameWindowProps) {
  const canvas = useRef<HTMLCanvasElement | null>(null);
  const lastFrame = useRef(0);

  const runGameLoop = useCallback(() => {
    window.requestAnimationFrame((currentFrame) => {
      const dt = currentFrame - lastFrame.current;
      game.update(dt);
      game.draw();
      lastFrame.current = currentFrame;

      runGameLoop();
    });
  }, [game]);

  useEffect(() => {
    if (!canvas.current) {
      return;
    }

    game.start(canvas.current!).then(runGameLoop);
  }, []);

  return <canvas ref={canvas} className="absolute inset-0" />;
}

// web/src/lib/components/GameWindow.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type Game from "$lib/game";

  let { game } = $props<{ game: Game }>();
  let canvas = $state();

  let lastFrame = 0;
  const runGameLoop = () => {
    window.requestAnimationFrame((currentFrame) => {
      const dt = currentFrame - lastFrame;
      game.update(dt);
      game.draw();
      lastFrame = currentFrame;

      runGameLoop();
    });
  };

  onMount(() => {
    game.start(canvas).then(runGameLoop);
  });
</script>

<canvas bind:this={canvas} class="absolute inset-0"></canvas>
